select * from "Customer" limit 25

-- Q1. What is the total revenue generated by male vs. female customer?
select gender, SUM(purchase_amount) as total_revenue 
from "Customer" 
group by gender

-- Q2. Which customer used the discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from "Customer" 
where discount_applied = 'Yes' and purchase_amount > (select AVG(purchase_amount)
														from "Customer")
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as average_review_rating
from "Customer"
group by item_purchased
order by average_review_rating desc
limit 5

-- Q4. Compare the average Purchase Amount between Standard and Express Shipping?
select shipping_type, ROUND(AVG(purchase_amount),2)
from "Customer"
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do suscribed customer spend more? Compare average spend and total revenue between suscribers and non suscribers.
select count(customer_id) as total_cusotmer, subscription_status, ROUND(AVG(purchase_amount),2) as average_spend, SUM(purchase_amount) as total_revenue
from "Customer"
group by subscription_status

-- Q6. which 5 products have the highest precentage of purchases with discount applied?
select item_purchased, ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from "Customer"
group by item_purchased
order by discount_rate desc
limit 5

-- Q7. Segment customer into New, Returning, and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
	ELSE 'LOYAL'
	END as customer_segment
from "Customer"
)
select customer_segment, count(*) as number_of_customer
from customer_type
group by customer_segment
order by number_of_customer 

-- Q8. What are the top 3 most purchased products within each category?
with item_count as(
select item_purchased, category, count(*) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rnk
from "Customer"
group by category, item_purchased
)
select item_rnk, category, item_purchased, total_orders from item_count
where item_rnk <=3

-- Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from "Customer"
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group, SUM(purchase_amount) as total_revenue
from "Customer"
group by age_group
order by total_revenue desc
